{% set name = "freva" %}
{% set version = "2208.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freva-{{ version }}.tar.gz
  sha256: b7a03de841359ac69c58e407157d6cb5d53a6fe4eb475c3d3455a02462f47b10

build:
  entry_points:
    - freva = freva.cli:main
    - freva-databrowser = freva.cli.databrowser:main
    - freva-esgf = freva.cli.esgf:main
    - freva-history = freva.cli.history:main
    - freva-plugin = freva.cli.plugin:main
    - freva-user-data = freva.cli.user_data:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - appdirs
    - pip
    - python >=3.7
  run:
    - appdirs
    - dask-core
    - django
    - gitpython
    - git
    - h5netcdf
    - humanize
    - lazy_import
    - mysqlclient
    - netcdf4
    - numpy
    - pandas
    - pandoc
    - pillow
    - pymysql
    - pypdf2 !=2.10.1
    - python >=3.7
    - requests
    - toml
    - toolz
    - typing_extensions
    - xarray

test:
  imports:
    - evaluation_system
    - freva
  commands:
    - pip check
    - freva --help
    - freva-databrowser --help
    - freva-esgf --help
    - freva-history --help
    - freva-plugin --help
    - freva-user-data --help
  requires:
    - pip

about:
  home: https://pypi.org/project/freva/
  summary: Free Evaluation and Analysis Framework (Freva)
  license: BSD-2-Clause
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - antarcticrainforest
